### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by yogeshsumman**

### CODE REVIEW

**Comment by AvineshTripathi** [comment]
can you give reason why you want this change

**Comment by yogeshsumman** [comment]
Yes, as we can see on the website, whenever there is a button and we try to click on it, the cursor is pointing in all but the mailing list subscribe button.

Additionally, from a perspective in the mailing list email part, the colour white seems a little off.

**Comment by AvineshTripathi** [comment]
#78  
I suppose this is the issue describing the needs of this PR?

**Comment by yogeshsumman** [comment]
yes

**Comment by AvineshTripathi** [comment]
can we shift the cursor more towards right(hard to see it), also once the area is clicked please make the "email address" written more lighter

**Comment by yogeshsumman** [comment]
Screenshot (76)

I did the cursor moving part tell me if it is fine or I should adjust it more  and working on the lighter part

**Comment by AvineshTripathi** [comment]
cursor a bit more towards right to be better just a little

**Comment by yogeshsumman** [comment]
Screenshot (85)
I think this looks good let me know

**Comment by AvineshTripathi** [comment]
LGTM 

cc @bhavyastar

**Pull request merged**
