### PR TITLE
Change the colour of Text in Buttons

### PR DESCRIPTION
**Pull request by shivarm**
## Screenshot

 

 
 
 
Screenshot (126)
Screenshot (127)

### CODE REVIEW

**Comment by samjn08** [comment]
Hey @shivam-sharma7, as mentioned in this issue https://github.com/kubesimplify/website/issues/47, we need to change the text colour of the email field only and not everywhere in the website. Please update the style accordingly.

Also change the colour of "Subscribe" text to maintain consistency in the design. Please see the attached image for reference.

Newsletter Section

cc @anubha-v-ardhan @AvineshTripathi

**Comment by shivam-sharma7** [comment]
> Hey @shivam-sharma7, as mentioned in this issue #47, we need to change the text colour of the email field only and not everywhere in the website. Please update the style accordingly.
> 
> Also change the colour of "Subscribe" text to maintain consistency in the design. Please see the attached image for reference.
> 
> Newsletter Section
> 
> Colour to be used for text: **#1B2731** / **rgb(27, 39, 49)**
> 
> cc @anubha-v-ardhan @AvineshTripathi

done 👍

**Comment by AvineshTripathi** [comment]
LGTM

cc @anubha-v-ardhan

**Review by verma-kunal — APPROVED** [review]
Looks good! 👍

**Comment by verma-kunal** [comment]
Thanks for contributing @shivam-sharma7 & for reviewing @AvineshTripathi 🙂

**Comment by shivam-sharma7** [comment]
> Thanks for contributing @shivam-sharma7 & for reviewing @AvineshTripathi 🙂

My pleasure

**Pull request merged**
