### PR TITLE
Fixed the PR request template

### PR DESCRIPTION
**Pull request by dipankardas011**
Signed-off-by: Dipankar Das <dipsonu10@hotmail.com>

### CODE REVIEW

**Comment by SuperAayush** [comment]
@dipankardas011  Can you elaborate on what have you fixed here?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question&nbsp; | &nbsp;**Tags:** Inefficient

**Comment by dipankardas011** [comment]
About the checkbox in the template

**Comment by AvineshTripathi** [comment]
cc @anubha-v-ardhan

**Review by Jai-Solania-29 — COMMENTED** [review]
Hey, @dipankardas011 Actually the changes You have made are not really required.

**Comment by dipankardas011** [comment]
Okay so closing
/close #65

**Pull request closed without merging**
