### PR TITLE
Adi

### PR DESCRIPTION
**Pull request by adityyaa-10**
Enhancement of Documentation.

### CODE REVIEW

**Comment by AvineshTripathi** [comment]
do you have a particular reason why you want to change the text?

**Review by shivam-sharma7 — APPROVED** [review]

**Comment by adityyaa-10** [comment]
Sir, I am new to contributing to open source, I thought enhancing the text would be a good contribution for a beginner like me.

**Comment by shivam-sharma7** [comment]
> Sir, I am new to contributing to open source, I thought enhancing the text would be a good contribution for a beginner like me.

@adityyaa-10  Don't call sir. But you have to make sure Why you want to change this?

**Comment by AvineshTripathi** [comment]
@adityyaa-10 we don't do sir/mam here and in most places around. You can address anyone with their name, its a best practice.

is the current text/documentaion incorrect?

**Comment by adityyaa-10** [comment]
It's not incorrect, but I feel it can be more presentable to people as it is right at the front of the website

**Comment by AvineshTripathi** [comment]
I think the current text is more grammatically correct, if you have some other point of view let me know

**Comment by saiyam1814** [comment]
Please create the issue and have a conversation there @adityyaa-10, also the PR name is something not clear what this PR does.

**Pull request closed without merging**
