### PR TITLE
Start learning button upgraded

### LINKED ISSUE #56: [FEATURE] changing the style of Start learning button
### Description

Please check the video. Can I add this style to this button. Then I will make a PR.

### Screenshots

https://user-images.githubusercontent.com/70086051/171104016-7d320def-f90b-4b6d-a227-548f3f70a594.mp4

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bishal7679**
## Fixes Issue #56 

a hover effect is added on the start learning button and also changed the border radius
An arrow is added in the button

## Screenshots
start learnin button

### CODE REVIEW

**Comment by anubha-v-ardhan** [comment]
All the buttons we have are rectangular with rounded corners. "Start learning" button after this change will look a little out of place in my opinion. Thoughts?

cc @AvineshTripathi

**Review by anubha-v-ardhan — COMMENTED** [review]
All the buttons we have are rectangular with rounded corners. "Start learning" button after this change will look a little out of place in my opinion. Thoughts?

cc @AvineshTripathi

**Comment by bishal7679** [comment]
@anubha-v-ardhan Yes I see but start learning button is like main button and highlightable on page. So we can add this style on it.

**Comment by AvineshTripathi** [comment]
I personally would not change the styles or anything different from the figma design until I get confirmation from JJ

**Comment by bishal7679** [comment]
@AvineshTripathi ok You can merge it after confirmation from JJ. No problem

**Comment by bishal7679** [comment]
@AvineshTripathi Can you ask him for this?

**Comment by bishal7679** [comment]
@AvineshTripathi I mentioned him on discord.

**Comment by dipankardas011** [comment]
Ui design should be accord ing to figma 

My opinion is that there should be no arrow with the 'start learning' button

**Comment by samjn08** [comment]
Hey @bishal7679, current design is fine. To maintain consistency in the design, we should not change it!
Also, instead of changing the color gradient on hover, you can darken the background using `box-shadow: inset 0em 0em 0em 10em rgba(0, 0, 0, 0.1);` and add `cursor:pointer;` on hover

cc @anubha-v-ardhan @AvineshTripathi

**Comment by bishal7679** [comment]
@samjn08 ok sure I will do it and will make another PR for this and also one thing Can I change the bolder from 600 to 560 becoz the text covering entire button which looking not so cool. Thanks for your kind reply @samjn08

**Comment by samjn08** [comment]
@bishal7679 Yes, go ahead! Please change font-weight to **500** for all the buttons in the website.

**Comment by bishal7679** [comment]
@samjn08 ok✌️

**Pull request closed without merging**
