### PR TITLE
Modified github readme

### PR DESCRIPTION
**Pull request by KrishAryan**
## Screenshots
!
screenshot (18)

screenshot (17)
screenshot (19)

### CODE REVIEW

**Comment by AvineshTripathi** [comment]
@verma-kunal @anubha-v-ardhan

**Review by chirag0002 — COMMENTED** [review]
Too many commits in a single PR, maybe squash these commits into 1 commit.

**Comment by KrishAryan** [comment]
@chirag0002 squashed the commits

**Comment by AvineshTripathi** [comment]
I don't think it is squashed & merged properly please have a look

**Comment by KrishAryan** [comment]
@AvineshTripathi can you merge it for this time because I seem to follow all the steps but it's still not squashing. Will take care from next time to not make so many commits

**Pull request closed without merging**
