### PR TITLE
Fixed About tab margin and newsletter button in navbar and added cursor to all 

### PR DESCRIPTION
**Pull request by bishal7679**
## Fixes Issue #73 #67 

[x] - Fixed About tab margin in navbar and added cursor to all 

## Screenshot
Screenshot (103)

### CODE REVIEW

**Review by AvineshTripathi — COMMENTED** [review]
Can you fix the alignment of navbar buttons as shown in below image

**Comment by bishal7679** [comment]
@AvineshTripathi Yeap sure! Then I have to make another PR

**Comment by AvineshTripathi** [comment]
You can fix in this PR if you want

**Comment by bishal7679** [comment]
@AvineshTripathi okay!

**Comment by bishal7679** [comment]
Now the alignment is looking right or not?
Have to change anything @AvineshTripathi ?
navbar-100

**Comment by bishal7679** [comment]
check it @AvineshTripathi after then  I will make changes into it.

**Comment by AvineshTripathi** [comment]
The `Newsletter` button is at perfect position while others are a bit up in comparison to Newsletter button i think

**Comment by bishal7679** [comment]
Okay no problem I will fix it again👍

**Comment by AvineshTripathi** [comment]
The image I sent was image from your PR which is in wrongly aligned

**Comment by bishal7679** [comment]
@AvineshTripathi okay I will ping you when It will be completed

**Comment by AvineshTripathi** [comment]
thank you for the contribution @bishal7679 

LGTM!!!
cc @verma-kunal @anubha-v-ardhan

**Review by verma-kunal — APPROVED** [review]
LGTM 👍

**Comment by verma-kunal** [comment]
Great work @bishal7679 !! And thank you for reviewing @AvineshTripathi ✨

**Comment by bishal7679** [comment]
Why you have merged it. I just sent the design for checking. I did not update the old PR.

**Pull request merged**
