### PR TITLE
feat: added remaining part of the home-page

### LINKED ISSUE #103: [FEATURE] Add remaining part of homepage
## some pointers
- We have the code ready but that is not combined with website repo 
- It uses bootstrap which we are currently not using so if bootstrap makes the entire website smooth throughout then please do use that all across homepage 

## steps to perform 
- copy paste the provide html and css in the https://github.com/kubesimplify/website/blob/main/src/components/HomepageFeatures/index.js
- see if we can achieve similar result without using bootstrap(the code provided uses bootstrap)
- make everything uniform 

Additional task to perform 
Make entire page in modular form like ambassador page 

### Screenshots

_No response_

### Additional information

I can send you the code for html and css, join our discord https://discord.gg/nNTaHn82 and say a hi

### PR DESCRIPTION
**Pull request by bhavyastar**
## Fixes Issue
Closes #103 

## Changes proposed

1. Add workshop container
2. Add Contribute to Blogs container
3. Add Apply to Ambassador Program container

## Screenshots
 
image

image

### CODE REVIEW

**Comment by AvineshTripathi** [comment]
I was expecting this to be in modular form, are you willing to modularize the code like we have for ambassadors or get this merge and later we modularize this part @bhavyastar

**Comment by bhavyastar** [comment]
Yes, like for responsiveness and modularity, we can make another issue and will work on this. What is your point of view?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by AvineshTripathi** [comment]
fine ignoring the responsiveness I'll do review tomorrow

**Comment by AvineshTripathi** [comment]
@bhavyastar merge this

**Pull request merged**
