### PR TITLE
created live-workshops page in react

### PR DESCRIPTION
**Pull request by sanyamjain04**
I have created live workshop page in React

- ✅ the code is scalable now 
- ✅ fixes responsiveness bugs.

## Screenshots
there is a youtube video in the box, i dont know why it's not showing in the box while taking screenshot.
localhost_3000_live-workshops

@AvineshTripathi Can you please review the PR?

### CODE REVIEW

**Comment by saiyam1814** [comment]
Why are we changing the live-workshops page @sanyamjain04 ?

**Comment by saiyam1814** [comment]
What is the process of adding a new workshop ? can you document that ? @verma-kunal adds these workshops so he should be aware of the changes

**Comment by sanyamjain04** [comment]
we have to create a new object and add it to the end of workshop data like this 

```javascript
export const workshopData = [
    {
      coverPhoto: chadMCrowell,
      workshopName: "Linux & Docker Fundamentals",
      date: "July 11th, 2022",
      time: "07:00 AM PT",
      workshopDesc:
        "This workshop aims to build a solid Linux and Docker foundation. You will learn about Linux fundamentals, containers and Docker.",
      workshopLink:
        "https://youtu.be/EUu1E_YKGTw",
        workshopStatus: "Watch Recording",
    },
    { ....
    }
    {
      coverPhoto: photo src,    //  import the photo of person 
      workshopName: "devops ",  // name of the workshop
      date: "July 18th, 2022",  // date of the workshop 
      time: "07:00 AM PT",  // time of the workshop
      workshopDesc:
        "This workshop helps you learn Kubernetes from scratch. Some of the topics include K8s fundamentals, Pods, Deployments, Services, Ingress & more.",   //  description about the workshop data here 
      workshopLink:
        "https://youtu.be/PN3VqbZqmD8", //  if the workshop is recorded then youtube link otherwise google form link here 
        workshopStatus: "Watch Recording",  // if workship is recorded then "Watch Recording " otherwise " Register now "
    }, 
```

**Comment by verma-kunal** [comment]
Lemme get back on this by EOD!

**Review by verma-kunal — APPROVED** [review]
This looks good to me!

**Comment by verma-kunal** [comment]
Thanks for contributing @sanyamjain04 ✨

**Pull request merged**
