### PR TITLE
margin of ambassador page conatainers add

### PR DESCRIPTION
**Pull request by shivam-sharma7**
- I hope now they are looking good.

## Screenshots
# Previous view
Screenshot (149)

Screenshot (150)

# Current view
Screenshot (151)

Screenshot (152)

### CODE REVIEW

**Comment by AvineshTripathi** [comment]
can we not make use of margin left or right with odd figures instead go for flex box with centeralized alignment to maintain the uniformity?

p.s. If that doesnot make sense lets connect on discord

**Comment by shivam-sharma7** [comment]
> can we not make use of margin left or right with odd figures instead go for flex box with centeralized alignment to maintain the uniformity?
 
@AvineshTripathi  We can use both, but i used margin left or right. I think 🤔 this one is good.

**Comment by AvineshTripathi** [comment]
I would prefer to keep the code away from hard coded positioning that is not uniform in all direction cause then sometimes reposiveness breaks in docusaurous, Hope that make sense

**Comment by shivam-sharma7** [comment]
> I would prefer to keep the code away from hard coded positioning that is not uniform in all direction cause then sometimes reposiveness breaks in docusaurous, Hope that make sense

Okay as you wish, what you have decided ?, Should i close this PR. ?

**Comment by saiyam1814** [comment]
I think this branch has a conflict and can be closed @shivam-sharma7

**Pull request closed without merging**
