### PR TITLE
set the margin of buttons

### PR DESCRIPTION
**Pull request by shivam-sharma7**
- set the margin of buttons.

issue: #153

Screenshot (140)

### CODE REVIEW

**Review by Jai-Solania-29 — COMMENTED** [review]
Hey, @shivam-sharma7 I think you should add some margin-top as well.

**Comment by Jai-Solania-29** [comment]
@shivam-sharma7 Can you provide the updated Screenshot?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question&nbsp; | &nbsp;**Tags:** Inefficient

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 Can you provide the updated Screenshot?
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** ❓ I have a question  |  **Tags:** Inefficient

Screenshot (141)

**Review by Jai-Solania-29 — APPROVED** [review]
LGTM 🚀

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by AvineshTripathi** [comment]
Thank you for the contribution
/lgtm

**Pull request merged**
