### PR TITLE
Setup for the About Page

### PR DESCRIPTION
**Pull request by dipankardas011**
Signed-off-by: Dipankar Das <dipsonu10@hotmail.com>

## Changes proposed

- [x] Linking of the About Page
- [x] addition of content 

[ ] - Not correct; marked as **not** done

## Screenshots
Screenshot from 2022-06-03 19-59-26

### CODE REVIEW

**Comment by dipankardas011** [comment]
Still working on

**Comment by AvineshTripathi** [comment]
will review by tom

**Comment by AvineshTripathi** [comment]
LGTM for the setup

**Comment by AvineshTripathi** [comment]
cc @verma-kunal

**Comment by verma-kunal** [comment]
Looks good! Thanks @dipankardas011 . Hope you are working on further building the page as well :)

**Pull request merged**
