### PR TITLE
feat: created half of student ambassador page for the website

### PR DESCRIPTION
**Pull request by mkgupta01**
Issue #19 

**Section Completed**
- hero section
- Criteria section
- Benefits section

This is how the website looks in **normal mode**
1/3
image
2/3
image
3/3
image

This is how the website looks in **inspect mode**
1/2
image
2/3
image
3/3
image

Things left
- Application section
- Student ambassadors gallery
- FAQs

### CODE REVIEW

**Comment by abh139** [comment]
Please also mention the issue number, like this issue will close which issue.
Although LGTM 👍

**Comment by AvineshTripathi** [comment]
Will review by EOD 
thank you for the contribution

**Comment by AvineshTripathi** [comment]
1. There is typo i  the title `Benifits`
2. `learnings` is not aligned properly below `Private Discord`

**Comment by mayankkuamr001** [comment]
Will rectify that 
@AvineshTripathi

**Comment by AvineshTripathi** [comment]
@mayankkuamr001 any updates?

**Comment by AvineshTripathi** [comment]
Hey @mayankkuamr001 we are with shortage of time for the completion of the website do you want some help regarding the same

**Comment by mayankkuamr001** [comment]
Hey @AvineshTripathi , I was waiting for the students ambassador component which I think is done by Bhavya once she had the list of ambassador. If you want I can make a PR for whole Kubesimply Ambassador page (beside ambassador component) by tomorrow.

**Comment by AvineshTripathi** [comment]
You don't have to wait for a PR for your PR so please complete and do a PR

**Comment by mayankkuamr001** [comment]
Fixed https://github.com/kubesimplify/website/pull/41#issuecomment-1122817854

Now website looks like
image

image

**Comment by AvineshTripathi** [comment]
LGTM 

cc @verma-kunal

**Comment by verma-kunal** [comment]
Yep! This looks good for now. We can add the student ambassador component later as well :)

**Pull request merged**
