### PR TITLE
Recreated About Page and Ambassador page

### PR DESCRIPTION
**Pull request by sanyamjain04**
I have made changes to the About pages. I have tried to keep the design as same as [Figma ](https://www.figma.com/proto/DNiw9eEdr4XWVO9i2NMtNK/Kubesimplify-Website?page-id=0%3A1&node-id=157%3A46&starting-point-node-id=157%3A46&scaling=scale-down-width&hide-ui=1) design 

I have created two new components newsletter and Teams and added them to the about page. I have also improved some code and CSS of other components in about page. I have added social media handles to the founder component.

|    Before     |  After |
|---------|:-------------:|
| kubesimplify github io_website_about_ | localhost_3000_website_about|

I have created a data.js file now we don't have to create a new team member card for every team member. we just have to add data to the teamData.js and it will create a new card just like the above image 
```javascript
   const teamData = [
    {
        name: 'Saiyam Pathak',
        coverPhoto: 'https://avatars.githubusercontent.com/u/8190114?v=4',
        role: 'Founder',
        twitterLink: 'https://twitter.com/saiyampathak',
        linkedinLink: 'https://www.linkedin.com/in/saiyampathak/',
        githubLink: 'https://github.com/saiyam1814'
    },
    {
        name: 'Saiyam',
        coverPhoto: 'https://avatars.githubusercontent.com/u/8190114?v=4',
        role: 'Founder',
        twitterLink: 'https://twitter.com/saiyampathak',
        linkedinLink: 'https://twitter.com/saiyampathak',
        githubLink: 'https://twitter.com/saiyampathak'
    },
]
```

Hello @AvineshTripathi , Can you please review the PR ?

### CODE REVIEW

**Comment by AvineshTripathi** [comment]
@saiyam1814 do we want profile to be added to website like above shown image ?

**Comment by saiyam1814** [comment]
Slider would bebetter, as this will keep taking more space as people gets added 
or you can create a separate page, Kubesimplify ambassadors that have this format and even if it keep getting added its fine

**Comment by AvineshTripathi** [comment]
+1 for the slider thing(I liked the profile card template for slider maybe you can use react slick up to you), now do we want this to be in about page or the ambassador page

**Comment by sanyamjain04** [comment]
hello @AvineshTripathi, I have created a slider in team component. i have not used any library. On screen width more than 1000px it will slide 2 cards and on screen width less than 1000px it will slide 1 card.
can you please review the changes ?

**Comment by saiyam1814** [comment]
So actually they are the Ambassadors , instead of team just put Kubesimplify ambassadors, also on the Kubesimplify ambassadors have all of the cards as a scroll bard , @AvineshTripathi can you provide him with picture, socials etc

**Comment by AvineshTripathi** [comment]
> also on the Kubesimplify ambassadors have all of the cards as a scroll bard 

same images both the places about as well as ambassador page, is that what you mean @saiyam1814

**Comment by saiyam1814** [comment]
YEs on the about page there can be the slider but if people want to see all on a single page then that can be on the Ambassadors page 
just like CNCF MAbassadors page

**Comment by sanyamjain04** [comment]
I have updated the ambassador page as this [Figma](https://www.figma.com/proto/DNiw9eEdr4XWVO9i2NMtNK/Kubesimplify-Website?page-id=0%3A1&node-id=792%3A3017&starting-point-node-id=157%3A46&scaling=scale-down-width&hide-ui=1) design

| Before | After |
| ----------- | ----------- |
|kubesimplify com_ambassadors_|localhost_3000_website_ambassadors (1)|

Hello @AvineshTripathi  can you please review this PR?
Now we just have to add data and it will work fine 

If the coverprofile url is wrong it will show the default Image as shown in above image

**Comment by AvineshTripathi** [comment]
remove the `newsletter`component from the `about` page Reason: it is already there on the home page

**Comment by sanyamjain04** [comment]
> remove the `newsletter`component from the `about` page Reason: it is already there on the home page

@AvineshTripathi i have removed the newletter component

**Comment by sanyamjain04** [comment]
Hello @AvineshTripathi is there anything left in this PR?

**Comment by AvineshTripathi** [comment]
there is a conflict in branches have a look

**Comment by sanyamjain04** [comment]
> there is a conflict in branches have a look

hello @AvineshTripathi ,Can we undo this commit ? This will solve the merge conflict.
I have breifly explain the reason why "undoing this commit is better solution" on discord DM
image

**Comment by AvineshTripathi** [comment]
@sanyamjain04 please add those points from discord to here also for documentation

**Comment by sanyamjain04** [comment]
> @sanyamjain04 please add those points from discord to here also for documentation

The reason why there is a merge conflict because of these two files
image
the code of two files also have changed in ⬇️  PR #182 
image
still the PR (182) does not solve all the bugs 
| Screenshots | of | Bugs  |       |
|----------|-------------|------|-----|
|Height of icons are incorrect|text is overlapping 👇🏻 (mobile - 320px)|icon and text is not responsive to its background div (tab - 768px)|apllication component is not aligned properly (tab 768px)|
|image |image |image|image

there are some other bugs too.
Now There are two ways we can **Solve the Merge Conflict** 
**Solution 1  ( faster and efficient )**:  We can undo PR 182 
**Solution 2 (slower and time taking)** : I have to fix these bugs in this PR ( #182 ) and refactor style file code again  

I am saying solution 1 is better bcz I have recreated the ambassador page in this PR so there is no need to solve the bugsif we undo the 182 PR .

**Comment by sanyamjain04** [comment]
@AvineshTripathi Is there anything left in this PR ?

**Pull request merged**
