### PR TITLE
Alignment of Homepage update

### PR DESCRIPTION
**Pull request by shivam-sharma7**
## Alignment of Homepage update #45

Screenshot (111)
Screenshot (112)

### CODE REVIEW

**Comment by AvineshTripathi** [comment]
Hey @shivam-sharma7 you would need to change all those `px` into % in order to solve this issue and wherever there is `margin-left` also include `margin-right`

**Comment by shivam-sharma7** [comment]
@AvineshTripathi i updated px to %.

**Comment by AvineshTripathi** [comment]
Will look into it

**Comment by AvineshTripathi** [comment]
The issues mentioned in the description is still present check it out once by `ctrl+` and `ctrl-`

**Comment by AvineshTripathi** [comment]
@shivam-sharma7 any updates or help you need

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 any updates or help you need

just check this one

**Comment by verma-kunal** [comment]
@shivam-sharma7 where are we at with the changes needed to be done here? 
Do you need any help with anything?

**Comment by verma-kunal** [comment]
Also, I would suggest making a **fresh PR** for this as changes from other PRs have also been added to this & are creating a conflict!
For every feature/change you make, it's always recommended to make a new branch & then work on that part

Hope you understand :)

**Pull request closed without merging**
