### PR TITLE
[FEATURE] Created remaining section the ambassadors page

### LINKED ISSUE #63: [FEATURE] Create remaining part of the ambassador page
### Description

The following components need to be created.
-  application component
- FAQs

### Screenshots

image

image

### PR DESCRIPTION
**Pull request by mayankkuamr001**
## Fixes Issue
Closes #63 

Section created
- Application section
- FAQs section

image

image

### CODE REVIEW

**Review by AvineshTripathi — COMMENTED** [review]
After initial review 
- The redirect link from home page on the `Student Ambassador` button is not set
- I don't see Navbar and footer for the page 
- 

Alignment is not proper

I liked the way the entire page is build in modular form

**Comment by AvineshTripathi** [comment]
Hey @mayankkuamr001 have you fixed the alignment as mentioned above

**Comment by AvineshTripathi** [comment]
Will review and get it merged day after tom, sorry for the delay

**Comment by AvineshTripathi** [comment]
Did my review(initials one)
change the `alt` parameter of various images to relevant one also still alignment is concern i will look to it

**Review by bhavyastar — COMMENTED** [review]
Try to add comments and make `alt` relevant to the images.

**Comment by mayankkuamr001** [comment]
Alignment in which section needs to be fixed.
https://github.com/kubesimplify/website/pull/77#issuecomment-1171614127




__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by AvineshTripathi** [comment]
When I say alignment i mean the responsiveness of the page. Sorry for the confusion

**Comment by AvineshTripathi** [comment]
I've created the issue #105 if you are fixing this page i can help you with fixing the entire website with the approach you take(in order to make things uniform)

**Comment by mayankkuamr001** [comment]
Fixed allignment 

image

image

image
 
image

image


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by mayankkuamr001** [comment]
https://github.com/kubesimplify/website/pull/77#issuecomment-1173875641

The position is absolute 😄

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by mayankkuamr001** [comment]
https://github.com/kubesimplify/website/pull/77#issuecomment-1173875641

The position is absolute 😄

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by bhavyastar** [comment]
Hey @AvineshTripathi, Are you reviewing this PR, Are we require any changes or we are good to go!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by AvineshTripathi** [comment]
will do final reviews today and get this going @bhavyastar

**Comment by AvineshTripathi** [comment]
> [#77 (comment)](https://github.com/kubesimplify/website/pull/77#issuecomment-1173875641)
> 
> The position is absolute smile
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** hammer_and_wrench This code needs a fix

can we change that to relative, also add `media` to even more smaller devices like smartphones, tabs?

**Comment by mayankkuamr001** [comment]
There should another design for smartphones. So I haven't added media queries for smartphones and was waiting for the design.

**Comment by bhavyastar** [comment]
@AvineshTripathi, Can we create another issue for responsiveness? Because there are many components for the website part which we need to make responsive.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by AvineshTripathi** [comment]
We already have one https://github.com/kubesimplify/website/issues/105 but I want this to be a team effort and we all have collectively address this issue

**Comment by AvineshTripathi** [comment]
Any reason why @mayankkuamr001  and @bhavyastar you both are merging the `main` into `ambassador`?

**Comment by bhavyastar** [comment]
Hey @AvineshTripathi, There are some conflicts in Navbar and I resolved these conflicts only! I guess I should merge the Pull request.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by AvineshTripathi** [comment]
LGTM 
Thanks @mayankkuamr001 for the contribution and sorry to keep you waiting 
Note: we need to work for the responsiveness

cc @bhavyastar @verma-kunal

**Pull request merged**
