### PR TITLE
Initial Website Setup - 1

### PR DESCRIPTION
**Pull request by verma-kunal**
An initial PR for setting up the base of our docusaurus website!

`Work-in-progress:`
- fixing some issues in the searchBar component 
- preparing a guide on "How to set up locally" for folks 
- hosting on gh-pages

Related to #5

### CODE REVIEW

**Review by SuperAayush — APPROVED** [review]

**Review by SuperAayush — APPROVED** [review]
LGTM 👍🏻

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Efficient

**Comment by AvineshTripathi** [comment]
Hey @verma-kunal i see some blogs in `blogs/ ` folder and tutorials in docs folder i was wondering if we need those things in our website. Are those mandatory components without which things won't work

**Comment by verma-kunal** [comment]
> Hey @verma-kunal i see some blogs in `blogs/ ` folder and tutorials in docs folder i was wondering if we need those things in our website. Are those mandatory components without which things won't work

Hmm, will surely look into this tomorrow @AvineshTripathi !! Thanks for pointing out :)

**Comment by saiyam1814** [comment]
I think we can cleanup a lot of stuff before putting the base template to the website , we do not needs the docs, tutorials as they can be looked up from the product website itself, we need to have a clean repo with basic structure and theme , then we start adding blogs and stuff

**Comment by verma-kunal** [comment]
> I think we can cleanup a lot of stuff before putting the base template to the website , we do not needs the docs, tutorials as they can be looked up from the product website itself, we need to have a clean repo with basic structure and theme , then we start adding blogs and stuff

Sure @saiyam1814 , will work on this part!

**Comment by anubha-v-ardhan** [comment]
Closing in favour of #16

**Pull request closed without merging**
