### PR TITLE
Add Dockerfile

### LINKED ISSUE #93: Addition of DockerFile
### Description

Wanted to add the docker file so that in future if we want to deploy anywhere we can easily do so

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dipankardas011**
## Fixes Issue

Closes #93  

## Changes proposed

- [x] Added
- [X] Tested

### CODE REVIEW

**Comment by dipankardas011** [comment]
@saiyam1814 ig addition of this might help in future

**Comment by saiyam1814** [comment]
@dipankardas011 can you add the screenshots of this working ?

**Comment by dipankardas011** [comment]
will share🙂

**Comment by dipankardas011** [comment]
> @dipankardas011 can you add the screenshots of this working ?

# Docker build
image

# Docker run
image

it is working on this branch (not sure because main and this branch has large gap of commits)

**Comment by dipankardas011** [comment]
@saiyam1814 is this branch mergable?

**Comment by dipankardas011** [comment]
@saiyam1814 Now all checks are done its working

**Comment by saiyam1814** [comment]
Nice! @AvineshTripathi can we merge this dockerfile ?

**Pull request merged**
