### PR TITLE
added Docusaurus link

### PR DESCRIPTION
**Pull request by souravsk**
## Fixes Issue

Docusaurus link was not added in the mentioned Style guide

## Changes proposed
Add the link to the website Docusaurus 

## Screenshots
[Screencast from 03-07-22 02:42:01 PM IST.webm](https://user-images.githubusercontent.com/33636054/177033334-fb157829-9a59-401a-802d-21a65337d023.webm)

## Note to reviewers
Can I See the website Layout?

### CODE REVIEW

**Comment by AvineshTripathi** [comment]
You can follow these steps mentioned to get output in your local device https://github.com/kubesimplify/website/blob/main/README.md also we have deployed the website on github pages checkout https://kubesimplify.github.io/website/

**Comment by AvineshTripathi** [comment]
LGTM!
thank you for the contributions

**Comment by souravsk** [comment]
thank you @AvineshTripathi

**Comment by AvineshTripathi** [comment]
cc @verma-kunal @bhavyastar

**Comment by saiyam1814** [comment]
Very straightforward PR, no need for waiting for it to be merged!

**Comment by souravsk** [comment]
Thanks, @saiyam1814 @verma-kunal

**Pull request merged**
