### PR TITLE
homepage images alignment fix

### PR DESCRIPTION
**Pull request by shivam-sharma7**
- homepage images alignment fix

### Previous changes.

Screenshot (178)

### Current change.

Screenshot (177)

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
review / @saiyam1814 @AvineshTripathi

**Comment by shivam-sharma7** [comment]
I hope, This is better than current situation of website homepage.

**Comment by AvineshTripathi** [comment]
will review this however this might take time cause I am caught up with some personal stuff

**Comment by shivam-sharma7** [comment]
> will review this however this might take time cause I am caught up with some personal stuff

i know exams

**Comment by shivam-sharma7** [comment]
review/ @AvineshTripathi @saiyam1814

**Comment by AvineshTripathi** [comment]
@shivam-sharma7 I still feel the original design looks better if you have some points on why we should add this then please tell

**Comment by AvineshTripathi** [comment]
hey @shivam-sharma7 the original design is what present in our figma design so it is actually a design

**Comment by AvineshTripathi** [comment]
@sanyamjain04 do you have the link

**Comment by sanyamjain04** [comment]
> @sanyamjain04 do you have the link

https://www.figma.com/proto/DNiw9eEdr4XWVO9i2NMtNK/Kubesimplify-Website?page-id=0%3A1&node-id=157%3A46&starting-point-node-id=157%3A46&scaling=scale-down-width&hide-ui=1

**Comment by shivam-sharma7** [comment]
Thanks @sanyamjain04 for sharing this link. I have seen but in figma design images alignment is not looking great and you can see my changes in following image. If this  is not good so you can close this PR.Thank you @AvineshTripathi 

Screenshot (177)

**Pull request closed without merging**
