### PR TITLE
Broken link title blog in website

### PR DESCRIPTION
**Pull request by shivam-sharma7**
- Fix: Broken link titled Blogs in website issue #42

### CODE REVIEW

**Comment by AvineshTripathi** [comment]
/hold 
because firstly let the navbar come and then we can think of links(I am not sure if we would require links which are in config file cause we would try to override them)

**Comment by anubha-v-ardhan** [comment]
@AvineshTripathi I think we can merge this fixing the current state of website. We can ofcourse remove things if not needed in future but the bugs on current deployment should also be fixed as it's public and folks (in and outside Kubesimplify) are able to visit it.

**Comment by AvineshTripathi** [comment]
@shivam-sharma7 why are we going for `https://kubesimplify.com` and not `/blog` any reason?

**Comment by shivam-sharma7** [comment]
Should I close this PR?

**Comment by shivam-sharma7** [comment]
But at home page blog  not found when we are click on that.

**Comment by AvineshTripathi** [comment]
@shivam-sharma7 on github pages when we click blog content we are redirected to the correct page, have a look there please and confirm

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 on github pages when we click blog content we are redirected to the correct page, have a look there please and confirm

Yes now it's working fine

**Comment by AvineshTripathi** [comment]
can we close this PR and issue related to this @shivam-sharma7

**Comment by shivam-sharma7** [comment]
> can we close this PR and issue related to this @shivam-sharma7

I closed.But check my other Opened PR

**Pull request closed without merging**
