### PR TITLE
PR Template

### LINKED ISSUE #14: Add PR template(s)
We need a PR template to guide folks for all they need to mention while making a PR.

### PR DESCRIPTION
**Pull request by abh139**
This PR will close #14 Issue

### CODE REVIEW

**Comment by AvineshTripathi** [comment]
do you think we should have a new PR on seperate branch

cc @anubha-v-ardhan

**Comment by anubha-v-ardhan** [comment]
> do you think we should have a new PR on seperate branch

@AvineshTripathi Any reason for making a new PR?

**Comment by AvineshTripathi** [comment]
The PR has commit that were involved in the issue template pr also if there
is no problem with addition of this PR then we can move ahead with it

**Comment by anubha-v-ardhan** [comment]
@AvineshTripathi GitHub isn't reporting any conflict, so we are safe to go with this PR. We'll also squash the commits before making this change equivalent to one commit.

**Review by anubha-v-ardhan — CHANGES_REQUESTED** [review]
change the file name to `pull_request_template.md`. GitHub only recognizes a markdown file as pull request template if it's named pull_request_template.
Refer [Creating a pull request template for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

Having spaces in file name is a bad practice in general too because whitespace characters are not supported by all operating systems and/or command line applications!

**Comment by abh139** [comment]
Updated

**Comment by verma-kunal** [comment]
Hey @abh139 , everything looks good! 
I think a section for adding relevant `screenshots` would be great as well 
If you agree on this, pls do add this in the end of the file
```
## Screenshots

<!-- Add all the screenshots which support your changes -->
```

**Comment by abh139** [comment]
> Hey @abh139 , everything looks good! I think a section for adding relevant `screenshots` would be great as well If you agree on this, pls do add this section before `Not to reviewers` heading
> 
> ```
> ## Screenshots
> 
> 
> ```
> 
> This should be good to go then!!

added

**Comment by verma-kunal** [comment]
Hey @abh139 , can you pls squash all your commits into 1 single commit? Thats always a good practice to follow before merging!
Let me know if you'll need any help :)

**Comment by anubha-v-ardhan** [comment]
@verma-kunal @abh139 
It's a good practice but fine if you don't too! We are able to squash the commits while merging a PR (drop down menu on merge button)

**Comment by verma-kunal** [comment]
> @verma-kunal @abh139 It's a good practice but fine if you don't too! We are able to squash the commits while merging a PR (drop down menu on merge button)

Agree with you! I think its always go to mention & make this a habbit to be used in any other open source org as well :)

**Comment by verma-kunal** [comment]
Thanks for contributing @abh139 !!

**Pull request merged**
