### PR TITLE
add nodejs workflow

### PR DESCRIPTION
**Pull request by AnuragThePathak**
Fixes Issue #27 

## Changes proposed
It adds the default nodejs workflow available from marketplace. I have commented the step to test as there are no tests present and it will result in failure.

### CODE REVIEW

**Comment by SuperAayush** [comment]
@AnuragThePathak have you tried making it run in your forked repo?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by AnuragThePathak** [comment]
Not in the forked repo, but I have used modified version of this workflow active in a few of my personal repositories. I can try running it if you want.

**Comment by AnuragThePathak** [comment]
@SuperAayush unfortunately it failed, I didn't notice that you people are not using react-scripts build. Btw any idea if it's because of docusaurus or not?

**Comment by AvineshTripathi** [comment]
We are already have a deploy workflow which does the deployment, do we have any specific reason why we are making a new workflow @AnuragThePathak

**Comment by AnuragThePathak** [comment]
@AvineshTripathi you are correct indeed. I just saw the issue open and hence wanted to work :)

**Comment by SuperAayush** [comment]
@AnuragThePathak I think @AvineshTripathi is right can you please close this PR 😄.
Thank you for showing interest 👍🏻.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by AnuragThePathak** [comment]
@SuperAayush the deployment workflow doesn't run when someone opens a PR or pushes to a existing one. From that perspective maybe the workflow I've added can be useful though.

**Comment by AnuragThePathak** [comment]
@AvineshTripathi instead of doing that, I simply removed the CI for node 12.x and the workflow is successful now

**Comment by AvineshTripathi** [comment]
@anubha-v-ardhan can you review this workflow change

**Comment by verma-kunal** [comment]
> @AvineshTripathi instead of doing that, I simply removed the CI for node 12.x and the workflow is successful now

Hey @AnuragThePathak , can you pls explain this change! It would help us understand things more clearly :)

**Comment by AvineshTripathi** [comment]
is there any problem adding these changes inside `deploy.yml` file

**Comment by AnuragThePathak** [comment]
> is there any problem adding these changes inside `deploy.yml` file

I have already answered your questions. If you are still not clear, let me explain in one of the simplest ways.

The problem is that the workflow defined in deploy.yml will only run in response to push events only. On the other hand, the workflow I added, runs against pull requests as well. `So it can help in finding out if the pushed code will build without an error or not.` But the workflow in deploy.yml can't do that.

**Comment by verma-kunal** [comment]
> 

Hey @AnuragThePathak , from what I am understanding, its basically **checking the code** that we are pushing to the repo. Acting as some kind of tests for vulnerabilities etc.
The `deploy.yml` file is basically just for deploying the pushed code automatically after merging a PR & displaying it on our website. 
Am going in the right direction here?

**Comment by AnuragThePathak** [comment]
@verma-kunal you exactly got what I meant!

**Review by verma-kunal — APPROVED** [review]
LGTM 👍

**Comment by verma-kunal** [comment]
Thanks for contributing @AnuragThePathak ✨

**Pull request merged**
