### PR TITLE
email logo size fixed

### PR DESCRIPTION
**Pull request by shivam-sharma7**
Email logo size fixed

issue: #220

kubesimlify1

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
review/ @AvineshTripathi @bhavyastar

**Comment by AvineshTripathi** [comment]
can you confirm if we still require this PR after the latest PR merged?

**Comment by shivam-sharma7** [comment]
> can you confirm if we still require this PR after the latest PR merged?

yes this is require you can check

**Comment by shivam-sharma7** [comment]
> can you confirm if we still require this PR after the latest PR merged?
Merged PR #218 not covering my changes

**Pull request merged**
