### PR TITLE
Deleted All five unused docusaurus images

### LINKED ISSUE #69: [CLEANUP] Delete unused default Docusaurus images
### What would you like to share?

We don't need the default Docusaurus images present in [static/img/](https://github.com/kubesimplify/website/tree/main/static/img). It would be better if we delete them to clean things up.

The images we aren't using are:

- [docusaurus.png](https://github.com/kubesimplify/website/blob/main/static/img/docusaurus.png)
- [logo.svg](https://github.com/kubesimplify/website/blob/main/static/img/logo.svg)
- [undraw_docusaurus_mountain.svg](https://github.com/kubesimplify/website/blob/main/static/img/undraw_docusaurus_mountain.svg)
- [undraw_docusaurus_react.svg](https://github.com/kubesimplify/website/blob/main/static/img/undraw_docusaurus_react.svg)
- [undraw_docusaurus_tree.svg](https://github.com/kubesimplify/website/blob/main/static/img/undraw_docusaurus_tree.svg)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bishal7679**

### CODE REVIEW

**Comment by code-hyker** [comment]
Then assign me to the task so that I can delete them

**Comment by bishal7679** [comment]
@AvineshTripathi Yeah why not?

**Comment by code-hyker** [comment]
SURE!  Sent from Mail for Windows From: Bishal DasSent: Tuesday, June 7, 2022 7:41 PMTo: kubesimplify/websiteCc: code-hyker; MentionSubject: Re: [kubesimplify/website] Deleted All five unused docusaurus images (PR ***@***.*** can you delete first three images?undraw_docusaurus_mountain.svgdocusaurus.pnglogo.svgand I will delete the last two so that both of our contribution will be upgraded.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by code-hyker** [comment]
SURE! Sent from Mail for Windows From: Avinesh TripathiSent: Tuesday, June 7, 2022 7:35 PMTo: kubesimplify/websiteCc: code-hyker; MentionSubject: Re: [kubesimplify/website] Deleted All five unused docusaurus images (PR #71) Hey @bishal7679 @code-hyker can you both divide the task and update your PR so that contributions for both are countedI see #70 PR deleting only one image while this PR deletes all the images, please discuss and update—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by code-hyker** [comment]
> @code-hyker can you delete first three images?
> 
> 1. [undraw_docusaurus_mountain.svg](https://github.com/kubesimplify/website/blob/main/static/img/undraw_docusaurus_mountain.svg)
> 2. [docusaurus.png](https://github.com/kubesimplify/website/blob/main/static/img/docusaurus.png)
> 3. [logo.svg](https://github.com/kubesimplify/website/blob/main/static/img/logo.svg)
> 
> and I will delete the last two so that both of our contribution will be upgraded.

SURE!

**Comment by AvineshTripathi** [comment]
Any updates?

**Comment by bishal7679** [comment]
@code-hyker are you there?
any update?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by code-hyker** [comment]
yes

**Comment by bishal7679** [comment]
@code-hyker ok then make a new PR with mentioned three images deleted and I also make a PR for remaining two.
let's do it.
P.S :- close all the PR and make new one

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Pull request closed without merging**
