### PR TITLE
Website Setup - 2

### PR DESCRIPTION
**Pull request by verma-kunal**
Updated the website files! 

Related to #5

### CODE REVIEW

**Comment by verma-kunal** [comment]
> @verma-kunal Is this PR supposed be an update on #13? Does this PR makes #13 redundant? Can we close #13?

This was supposed to be a new PR with only a few addons from the previous one! But i guess there was an issue while making this PR & all the previous PR commits have also been added in this PR

if thats the case, i think we can close #13 & go with this one

**Comment by anubha-v-ardhan** [comment]
PR #13 was made from your `main` branch. So my guess is when you branched `dev-kunal` off of it, all the commits got carried from `main` to `dev-kunal`.

Make sure to clean the `main` on your fork to avoid the same in future. For now we can use this PR, I'm closing #13 :)

**Comment by saiyam1814** [comment]
Looks good, the tutorials folder always gets regenerated @verma-kunal ?

**Comment by verma-kunal** [comment]
> Looks good, the tutorials folder always gets regenerated @verma-kunal ?

Yes! The /blog & /tutorials sections were getting regenerated everytime we deleted those! But we worked around this & was able to completely remove the /blog section & renamed /tutorials to `Notes`

The only issue now is that, whenever we run `npm run start` i.e. start the dev environment, there is a warning like:
`Warn: `blogDir` doesn't exist: "/Users/kunalverma/Desktop/My Stuff/OS-Repos/KubeSimplify/kubesimplify-web/blog".`
which is quite logical as we have deleted the folder but there might be something internally that is detecting this particular issue!
Although, the site looks clean & this is not bothering with the other parts of our code! So, i think we can move forward with this

This is a preview of the site right now:

https://user-images.githubusercontent.com/72245772/165700005-8c530d10-ec12-466e-8c8e-6cca04432126.mov

**Comment by saiyam1814** [comment]
in the files changed section I still see 
image
Tutorials folder, can you recheck @verma-kunal

**Comment by verma-kunal** [comment]
Hey @saiyam1814 , can you pls check now! I think we forgot to delete the images related to the tutorials folder.
Done that now!
Also, I saw that whenever we start the dev environment, some JSON files are being auto-generated in `/docs` folder, which we had deleted yesterday but have been restored & I don't think that these can be deleted! 
So, have made a commit for those as well 

Let me know any other changes needed :)

**Comment by saiyam1814** [comment]
LGTM

**Pull request merged**
