### PR TITLE
Start learning button upgraded 2.0

### LINKED ISSUE #56: [FEATURE] changing the style of Start learning button
### Description

Please check the video. Can I add this style to this button. Then I will make a PR.

### Screenshots

https://user-images.githubusercontent.com/70086051/171104016-7d320def-f90b-4b6d-a227-548f3f70a594.mp4

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bishal7679**
## Changes proposed

[x] - Hover effect added and cursor changed to pointer

## Screenshot

Screenshot (102)

### CODE REVIEW

**Comment by AvineshTripathi** [comment]
LGTM

**Comment by bishal7679** [comment]
@AvineshTripathi @verma-kunal 
Can You merge it?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Review by verma-kunal — APPROVED** [review]
LGTM! 👍

**Comment by verma-kunal** [comment]
Thanks for contributing @bishal7679 🚀

**Pull request merged**
