### PR TITLE
Remove buy me coffee button

### PR DESCRIPTION
**Pull request by shivam-sharma7**
issues #117

 

## Screenshots
Screenshot (135)

### CODE REVIEW

**Comment by AvineshTripathi** [comment]
move the button towards center

**Comment by shivam-sharma7** [comment]
> 

- done

**Comment by AvineshTripathi** [comment]
will do the review

**Comment by AvineshTripathi** [comment]
Hey @shivam-sharma7 are you sure the commits are making the footer responsive if not then please try to make it responsive

**Comment by shivam-sharma7** [comment]
> Hey @shivam-sharma7 are you sure the commits are making the footer responsive if not then please try to make it responsive

Hey @AvineshTripathi my commits are not affecting responsiveness of footer.

**Pull request closed without merging**
