### PR TITLE
The spacing of email address and icon size update

### PR DESCRIPTION
**Pull request by shivam-sharma7**
# Fixes Issue: #138
 

## Screenshots
# Previous View 

Screenshot (146)

# Current View

Screenshot (147)

### CODE REVIEW

**Comment by AvineshTripathi** [comment]
@shivam-sharma7  can you send me different views for the same i.e. mobile view or less width in inspect?

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 can you send me different views for the same i.e. mobile view or less width in inspect?

@AvineshTripathi I believe this width good for mobile.
Screenshot (154)

**Comment by AvineshTripathi** [comment]
ithink we should add

**Comment by shivam-sharma7** [comment]
> ithink we should add

@AvineshTripathi okay i am going to add this.

**Comment by saiyam1814** [comment]
Can you recheck if this issue still persists @shivam-sharma7 ?

**Pull request closed without merging**
