### PR TITLE
feat: add navbar for website

### LINKED ISSUE #37: feat: add navbar for website
Navbar for the website where users can redirect to different other web pages.

### PR DESCRIPTION
**Pull request by bhavyastar**
Closes #37 
Built Navbar for all the webpages 
This is how Navbar looks in full-screen mode : 

Screenshot (356)

This is how Navbar looks in inspect modes : 

Screenshot (352)

Screenshot (353)

cc @verma-kunal @AvineshTripathi @SuperAayush

Note to reviewers : Thanks in advance for reviewing my code 😄

### CODE REVIEW

**Comment by AvineshTripathi** [comment]
@bhavyastar Your parent container for `About` and `contact` is not perfectly aligned with the other two

**Comment by bhavyastar** [comment]
> @bhavyastar Your parent container for `About` and `contact` is not perfectly aligned with the other two

I modified some code, Can you please again review it?

**Comment by AvineshTripathi** [comment]
I can see the hover  animation is not there on learn and community do you want to add it now or later

**Comment by bhavyastar** [comment]
> I can see the hover animation is not there on learn and community do you want to add it now or later

Because hovering animation is only in website preview Figma not in the mockup part. So, when I update the code for the about page then I will do this after discussion with JJ.Thompson. So, for now, it is final.  Any other thing?

**Comment by AvineshTripathi** [comment]
I think we can resize the logo and title into bit smaller one and apart from this we can align the button bit more towards right, currently it seems to be more towards center

**Comment by bhavyastar** [comment]
Okay, I will make these small changes with the about page pull request! Is it okay? @AvineshTripathi

**Comment by verma-kunal** [comment]
Hey @bhavyastar , have all the suggestions made by @AvineshTripathi been implemented to this? 

> I think we can resize the logo and title into bit smaller one and apart from this we can align the button bit more towards right, currently it seems to be more towards center

What about this one? ☝🏻

**Comment by bhavyastar** [comment]
> Hey @bhavyastar , have all the suggestions made by @AvineshTripathi been implemented to this?
> 
> > I think we can resize the logo and title into bit smaller one and apart from this we can align the button bit more towards right, currently it seems to be more towards center
> 
> What about this one? ☝🏻

Ya, this one is also fixed. You can merge it!

**Comment by Shivansh-yadav13** [comment]
@bhavyastar pls show SS of the latest change

**Comment by bhavyastar** [comment]
> @bhavyastar pls show SS of the latest change

## 
Screenshot (372)

**Comment by AvineshTripathi** [comment]
LGTM 

cc @verma-kunal

**Comment by verma-kunal** [comment]
Thanks for contributing @bhavyastar & for reviewing this @AvineshTripathi !!

**Pull request merged**
