### PR TITLE
footer css fix

### PR DESCRIPTION
**Pull request by thangamariappan19**
screenshot-kubesimplify github io-2022 07 03-22_30_30

### CODE REVIEW

**Comment by AvineshTripathi** [comment]
can you fix this as well @thangamariappan19

**Comment by thangamariappan19** [comment]
@verma-kunal @bhavyastar

**Comment by AvineshTripathi** [comment]
The bottom white line with social logos are suppose to be inside the footer component on the back background, i hope that made sense

**Comment by thangamariappan19** [comment]
> The bottom white line with social logos are suppose to be inside the footer component on the back background, i hope that made sense
screenshot-localhost_3000-2022 07 05-21_50_05

**Comment by thangamariappan19** [comment]
Can you pls review and approve it,if its ok. @AvineshTripathi @bhavyastar @verma-kunal

**Comment by bhavyastar** [comment]
Hello, @thangamariappan19, I will review this and then suggests you some changes if it is required.

**Comment by AvineshTripathi** [comment]
Hey @thangamariappan19 from initial looks I would say that the social handle icon part can be shifted a bit left cause in the image above it look to be right of the above horizontal line, also we can remove spaces below the line and below the icons, email, kubesimplify titile 

p.s. More detailed analysis would be done by @bhavyastar

**Review by bhavyastar — COMMENTED** [review]
The changes proposed by @AvineshTripathi need to be done, after that, we all are good to go! @thangamariappan19

**Comment by AvineshTripathi** [comment]
@bhavyastar merge this will do minor fixes later in other PRs

**Comment by AvineshTripathi** [comment]
@verma-kunal merge this please

**Pull request merged**
